CREATE TABLE Patients (
	[PatientId] INT PRIMARY KEY IDENTITY(1,1),
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[DateOfBirth] DATE,
	[Gender] CHAR(1),
	[ContactNumber] NVARCHAR(20),
	[Address] NVARCHAR(255)
)

CREATE TABLE Doctors (
	[DoctorId] INT PRIMARY KEY IDENTITY(1,1),
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[Specialization] NVARCHAR(100),
	[ContactNumber] NVARCHAR(20),
	[Email] NVARCHAR(100)
)

CREATE TABLE Appointments (
	[ApppointmentId] INT PRIMARY KEY IDENTITY(1,1),
	[PatientId] INT,
	[DoctorId] INT,
	[RecordDate] DATETIME,
	[Diagnosis] NVARCHAR(255),
	[Treatment] NVARCHAR(500),
	CONSTRAINT FK_PatientId FOREIGN KEY (PatientId) REFERENCES Patients(PatientId),
	CONSTRAINT FK_DoctorId FOREIGN KEY (DoctorId) REFERENCES Doctors(DoctorId)
)

CREATE TABLE MedicalRecords (
	[RecordId] INT PRIMARY KEY IDENTITY(1,1),
	[PatientId] INT,
	[DoctorId] INT,
	[RecordDate] DATETIME,
	[Diagnosis] NVARCHAR(255),
	[Treatment] NVARCHAR(500),
	CONSTRAINT FK_PatientId_MR FOREIGN KEY (PatientId) REFERENCES Patients(PatientId),
	CONSTRAINT FK_DoctorId_MR FOREIGN KEY (DoctorId) REFERENCES Doctors(DoctorId)
)

CREATE TABLE Billing (
	BillId INT PRIMARY KEY IDENTITY(1,1),
	[PatientId] INT,
	[BillDate] DATETIME,
	[Amount] DECIMAL(10,2),
	CONSTRAINT FK_PatientId_Billing FOREIGN KEY (PatientId) REFERENCES Patients(PatientId)
)

CREATE TABLE Rooms (
    RoomId INT PRIMARY KEY IDENTITY(1,1),
    RoomNumber NVARCHAR(20) NOT NULL,
    RoomType NVARCHAR(50) NOT NULL,
    IsOccupied BIT
)

CREATE TABLE RoomCosts (
    RoomCostId INT PRIMARY KEY IDENTITY(1,1),
    RoomType NVARCHAR(50) NOT NULL,
    DailyRate DECIMAL(10,2),
    WeeklyRate DECIMAL(10,2)
)

CREATE TABLE VIPRooms (
    VIPRoomId INT PRIMARY KEY IDENTITY(1,1),
    RoomId INT,
    SpecialAmenities NVARCHAR(255),
    CONSTRAINT FK_RoomId FOREIGN KEY (RoomId) REFERENCES Rooms(RoomId)
)

CREATE TABLE Users (
	Id INT PRIMARY KEY IDENTITY(1,1),
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	UserName NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Password NVARCHAR(100) NOT NULL,
	DateOfCreation DATETIME2 NOT NULL
)


ALTER TABLE Patients ALTER COLUMN [DateOfBirth] DATE NOT NULL
ALTER TABLE Patients ALTER COLUMN [Gender] CHAR(1) NOT NULL
ALTER TABLE Patients ALTER COLUMN [ContactNumber] NVARCHAR(20) NOT NULL
ALTER TABLE Patients ALTER COLUMN [Address] NVARCHAR(255) NOT NULL

ALTER TABLE Doctors ALTER COLUMN [Specialization] NVARCHAR(100) NOT NULL
ALTER TABLE Doctors ALTER COLUMN [ContactNumber] NVARCHAR(20) NOT NULL
ALTER TABLE Doctors ALTER COLUMN [Email] NVARCHAR(100) NOT NULL

ALTER TABLE Appointments ALTER COLUMN [PatientId] INT NOT NULL
ALTER TABLE Appointments ALTER COLUMN [DoctorId] INT NOT NULL
ALTER TABLE Appointments ALTER COLUMN [RecordDate] DATETIME NOT NULL
ALTER TABLE Appointments ALTER COLUMN [Diagnosis] NVARCHAR(255) NOT NULL
ALTER TABLE Appointments ALTER COLUMN [Treatment] NVARCHAR(500) NOT NULL


ALTER TABLE MedicalRecords ALTER COLUMN [PatientId] INT NOT NULL
ALTER TABLE MedicalRecords ALTER COLUMN [DoctorId] INT NOT NULL
ALTER TABLE MedicalRecords ALTER COLUMN [RecordDate] DATETIME NOT NULL
ALTER TABLE MedicalRecords ALTER COLUMN [Diagnosis] NVARCHAR(255) NOT NULL
ALTER TABLE MedicalRecords ALTER COLUMN [Treatment] NVARCHAR(500) NOT NULL


ALTER TABLE Billing ALTER COLUMN [PatientId] INT NOT NULL
ALTER TABLE Billing ALTER COLUMN [BillDate] DATETIME NOT NULL
ALTER TABLE Billing ALTER COLUMN [Amount] DECIMAL(10,2) NOT NULL


ALTER TABLE Rooms ALTER COLUMN [RoomNumber] NVARCHAR(20) NOT NULL
ALTER TABLE Rooms ALTER COLUMN [RoomType] NVARCHAR(50) NOT NULL
ALTER TABLE Rooms ALTER COLUMN [IsOccupied] BIT NOT NULL


ALTER TABLE RoomCosts ALTER COLUMN [RoomType] NVARCHAR(50) NOT NULL
ALTER TABLE RoomCosts ALTER COLUMN [DailyRate] DECIMAL(10,2) NOT NULL
ALTER TABLE RoomCosts ALTER COLUMN [WeeklyRate] DECIMAL(10,2) NOT NULL


ALTER TABLE VIPRooms ALTER COLUMN [RoomId] INT NOT NULL
ALTER TABLE VIPRooms ALTER COLUMN [SpecialAmenities] NVARCHAR(255) NOT NULL

